# === CONFIGURABLE SETTINGS === 
# CHANGE IF NEEDED, DEFAULT LIST OF SETTINGS CAN BE FOUND BELOW

# Z-TRIMMING (global height filtering before clustering)
ENABLE_Z_TRIMMING = True
Z_TRIM_MARGIN = 0.02  # in meters

# WALL PCA SPLITTING (for split walls that are obstructed)
USE_WALL_PCA_SPLIT = False

# WALL MERGING (merge nearby bounding boxes along wall direction)
MERGE_WALL_BOXES = True

# FLOOR/CEILING OUTLIER FILTERING (cluster rejection based on z-distribution)
FILTER_OUTLIERS_BY_Z_RATIO = True
MAX_Z_OUTLIER_RATIO_PILLAR = 0.01
MAX_Z_OUTLIER_RATIO_WALL = 0.05

# WALL BOUNDING BOX THICKNESS (fixed non-vertical dimension of wall boxes)
FIXED_WALL_THICKNESS = 0.15  # in meters

# STRETCH_BBOX_VERTICALLY (override bbox Z-extent to span full room height)
STRETCH_VERTICALLY = True

# MINIMUM CLUSTER SIZE FOR BBOX FITTING
MIN_CLUSTER_SIZE = 30

# MINIMUM VERTICAL EXTENT OF CLUSTERS (in meters)
MIN_VERTICAL_EXTENT_PILLAR = 0.2
MIN_VERTICAL_EXTENT_WALL = 0.1

# WALL SPLITTING ECCENTRICITY THRESHOLD (for experimental PCA split)
WALL_SPLIT_ECC_THRESHOLD = 5.0

# REMOVE BOXES BELOW LENGTH THRESHOLD (to avoid fitting boxes to tiny walls)
MIN_WALL_LENGTH_FOR_BBOX = 0.5  # in meters

# DUPLICATE BOUNDING BOX FILTERING (across models)
DUPLICATE_CENTER_DISTANCE_THRESHOLD = 0.5  # in meters

# PROBABILITY THRESHOLD FOR A POINT TO BE MARKED AS MISMATCHED
THRESHOLD = 0.6

# VALID BBOX DIMENSIONS (used in is_valid_* functions inside bounding_box_helpers.py)
# Pillar bounding box constraints
VALID_PILLAR_DX_MIN = 0.1
VALID_PILLAR_DX_MAX = 3.0
VALID_PILLAR_DY_MIN = 0.1
VALID_PILLAR_DY_MAX = 3.0
VALID_PILLAR_DZ_MIN = 2.0
VALID_PILLAR_DZ_MAX = 10.0

# Wall bounding box constraints
VALID_WALL_THICKNESS_MIN = 0.05
VALID_WALL_THICKNESS_MAX = 0.25
VALID_WALL_LENGTH_MIN = 0.5
VALID_WALL_LENGTH_MAX = 50.0
VALID_WALL_HEIGHT_MIN = 2.0
VALID_WALL_HEIGHT_MAX = 10.0

# === DEFAULT VALUES (for reference) ===
# ENABLE_Z_TRIMMING = True
# Z_TRIM_MARGIN = 0.02
# USE_WALL_PCA_SPLIT = False
# MERGE_WALL_BOXES = True
# FILTER_OUTLIERS_BY_Z_RATIO = True
# MAX_Z_OUTLIER_RATIO_PILLAR = 0.01
# MAX_Z_OUTLIER_RATIO_WALL = 0.05
# FIXED_WALL_THICKNESS = 0.15
# STRETCH_VERTICALLY = True
# MIN_CLUSTER_SIZE = 30
# MIN_VERTICAL_EXTENT_PILLAR = 0.2
# MIN_VERTICAL_EXTENT_WALL = 0.1
# WALL_SPLIT_ECC_THRESHOLD = 5.0
# MIN_WALL_LENGTH_FOR_BBOX = 0.5
# DUPLICATE_CENTER_DISTANCE_THRESHOLD = 0.5
# THRESHOLD = 0.6
# # Pillar bounding box constraints
# VALID_PILLAR_DX_MIN = 0.1
# VALID_PILLAR_DX_MAX = 3.0
# VALID_PILLAR_DY_MIN = 0.1
# VALID_PILLAR_DY_MAX = 3.0
# VALID_PILLAR_DZ_MIN = 2.0
# VALID_PILLAR_DZ_MAX = 10.0

# # Wall bounding box constraints
# VALID_WALL_THICKNESS_MIN = 0.05
# VALID_WALL_THICKNESS_MAX = 0.25
# VALID_WALL_LENGTH_MIN = 0.5
# VALID_WALL_LENGTH_MAX = 50.0
# VALID_WALL_HEIGHT_MIN = 2.0
# VALID_WALL_HEIGHT_MAX = 10.0